# exclude un-modified external software from Codacy analysis
exclude_paths:
  - lib/html/static/css/bootstrap*
  - lib/html/static/js/bootstrap*
  - lib/html/static/css/jquery*
  - lib/html/static/js/livestamp.min.js
  - lib/html/static/js/moment.min.js
  - lib/python/isodatetime/
  - etc/tutorial/cylc/python/png.py
