# Configuration for running Rose test battery on Travis CI
# See https://travis-ci.org/ for more info.

---
language: python
python:
    - 3.7
dist: xenial


before_install:
  - export PATH="$PWD/.travis:$PATH"

after_success:
  - now report_coverage

jobs:
  include:
    - name: "Unit Tests"
      install:
        - now install coverage cylc linters
      script:
        - now style_test
        - now unit_test

    - name: "Test Battery"
      install:
        - now install coverage cylc fcm
      script:
        - now test_battery

    - name: "Documentation"
      install:
        - now install sphinx coverage
      script:
        - docs_test
        - docs_build
