name: Build

# build the project whenever the configuration is changed

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'README.md'       # check markdown is valid
      - 'MANIFEST.in'     # check packaging
      - 'pyproject.toml'  # check deps and project config
      - '.gitignore'
      - '.github/workflows/build.yml'

env:
  FORCE_COLOR: 2

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python: ['3.8', '3.9', '3']
        include:
          - os: 'ubuntu-22.04'
            python: '3.7'
          - os: 'macos-latest'
            python: '3.8'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build
        uses: cylc/release-actions/build-python-package@v1

      - name: Inspect
        run: |
          unzip -l dist/*.whl | tee files
          grep 'metomi_rose.*.dist-info/COPYING' files
          grep 'metomi/rose/etc' files
          grep 'metomi/rosie/lib' files
          grep 'metomi/rose/scripts' files
          # grep 'metomi/rose/py.typed' files  # TODO
